--!strict
return function()
	local ImageProcessor = require(script.Parent.Parent.DockWidgetGui.services.ImageProcessor)

	describe("ImageProcessor.clampZoom", function()
		it("clamps below 0.25", function()
			expect(ImageProcessor.clampZoom(0.1)).to.equal(0.25)
		end)
		it("clamps above 4", function()
			expect(ImageProcessor.clampZoom(10)).to.equal(4)
		end)
		it("passes through valid zoom", function()
			expect(ImageProcessor.clampZoom(1.5)).to.equal(1.5)
		end)
	end)

	describe("ImageProcessor.snapToGrid", function()
		it("rounds to nearest 16", function()
			expect(ImageProcessor.snapToGrid(18, 16)).to.equal(16)
			expect(ImageProcessor.snapToGrid(25, 16)).to.equal(32)
			expect(ImageProcessor.snapToGrid(-7, 16)).to.equal(0)
		end)
		it("returns same value when grid = 0", function()
			expect(ImageProcessor.snapToGrid(13, 0)).to.equal(13)
		end)
	end)

	describe("ImageProcessor.wrapRotation", function()
		it("wraps 200 to -160", function()
			expect(ImageProcessor.wrapRotation(200)).to.equal(-160)
		end)
		it("wraps -200 to 160", function()
			expect(ImageProcessor.wrapRotation(-200)).to.equal(160)
		end)
		it("passes through valid rotation", function()
			expect(ImageProcessor.wrapRotation(45)).to.equal(45)
			expect(ImageProcessor.wrapRotation(-90)).to.equal(-90)
			expect(ImageProcessor.wrapRotation(180)).to.equal(180)
		end)
	end)

	describe("ImageProcessor.clampPosition", function()
		it("clamps offset to ±half resolution", function()
			local pos = { offsetX = 1000, offsetY = -1000, zoom = 5, rotation = 0, snapEnabled = false }
			local out = ImageProcessor.clampPosition(pos, 512)
			expect(out.offsetX).to.equal(256)
			expect(out.offsetY).to.equal(-256)
			expect(out.zoom).to.equal(4)
		end)

		it("snap to grid when snapEnabled is true", function()
			local pos = { offsetX = 17, offsetY = -23, zoom = 1, rotation = 0, snapEnabled = true }
			local out = ImageProcessor.clampPosition(pos, 512)
			expect(out.offsetX).to.equal(16)
			expect(out.offsetY).to.equal(-16)
		end)
	end)
end